### ISSUE TITLE
webpackChunkName for Polyfill

### ISSUE THREAD

**Issue by RyanMulready** [GrabarzUndPartner/nuxt-custom-elements#159]
https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/65f7512ea148b51f57db787f5eae9730bb0cee98/lib/tmpl/entry.js#L11

The result of this line when webpack chunking is enabled is a file output of `1.js`. It should have a chunkname `/* webpackChunkName: "document-register-element" */` defined.  Even then it would be better if there was a way to tell the build to not chunk this file and include it in our entry point.

**Comment by ThornWalli** [comment]
Hello,

The chunking is caused by the `import`, the reason for this is to keep the file sizes small for loading. Preferably one more than one blocking.

If the Polyfill is not needed, it can be deactivated with `polyfill: false`. So this import will not appear in the build anymore.

But now the idea would be to limit the Polyfill in the background to the `client` build and integrate it there directly. Then the `modern` build is clean.

**Comment by ThornWalli** [comment]
Now the polyfill is directly in the `client` build. Polyfill in the `modern` build is not needed.

**Reports:** 

https://grabarzundpartner.github.io/nuxt-custom-elements/reports/webpack/nuxt-custom-elements/component-app-abstract/client.html
https://grabarzundpartner.github.io/nuxt-custom-elements/reports/webpack/nuxt-custom-elements/component-app-abstract/modern.html
