### ISSUE TITLE
How to use the styles in vue files

### ISSUE THREAD

**Issue by buremba** [GrabarzUndPartner/nuxt-custom-elements#211]
There is the following info in the README:
```
⚠️  Important: CSS from the SingleFile (.vue) cannot be used, this will be included by the vue-loader by using the style-loader.
```

If it's not supported, what's the workaround? For reference, we have around 40 components that you these inline CSS in Vue and we would like to avoid duplication.

**Comment by ThornWalli** [comment]
Just so I understand correctly, there are about 40 components and all of them should have ShadowCSS?

For the Shadow Use Case I have created an example:

**Component with limited style tag usage:** 
https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/feature/shadow-css/example/components/apps/AppShadow.vue

**Two components with different import of ShadowCSS:**
https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/feature/shadow-css/example/nuxt.config.js#L68

If you want to use the SingleFile Style tag, you would have to query it for a component. Unfortunately this seems to be not so easy, because the evaluation of the Vue-File is done in the `vue-loader` and you don't get any `css` back via the `import`. Unless you write the style imports created by the `vue-loader `itself.

https://github.com/GrabarzUndPartner/nuxt-custom-elements/blob/feature/shadow-css/lib/tmpl/entry.js#L11

**Example:** !raw-loader!vue-loader!@/components/apps/AppShadow?vue&type=style&index=0&lang=css

So you get the `css` from the first style tag with lang `css`. But what is missing here is the respective loader for compiling (e.g. PostCSS)

**Comment by buremba** [comment]
Thanks for the answer, @ThornWalli. I tried your fork but from what I understood, it only takes care of including the styles of the imported Vue component, but all the styles that are being used hierarchically. Think of the following use-case:

main.vue:
```
<template>
  <other-component />
</template>

<script>
import otherComponent './other-component'

export default {
  components: {otherComponent}
}
</script>
```

other-component.vue:
```
<template>
  <other-component />
</template>

<script>
export default {
}
</script>

<style>
  .elem {
      background:red
  }
</style>
```

And here is the `entries` of module config:
```
[         
           {
            name: 'main',
            tags: [
              {
                name: 'main',
                path: '@/main.vue',
                options: {
                  props: ['prop1', 'prop2'],
                }
              }
            ]
          }
]
```

In this case, I expect the web-component to include the styles in `other-component.vue` but it doesn't seem to include it. I can remove all the inline styles and convert it to `<style lang="css" src="./stylesforothercomponent.css"></style>` but that doesn't help either.

**Comment by ThornWalli** [comment]
Am a little confused what you mean :)

Can you build me an example in a sandbox?

I have a report from an entry build here: 
https://grabarzundpartner.github.io/nuxt-custom-elements/reports/webpack/nuxt-custom-elements/component-app-i18n/modern.html

There the GithubCorner is imported async, so the style is in the chunk.

![image](https://user-images.githubusercontent.com/8287751/102274469-3bd32d00-3f24-11eb-8107-19e3fa27aecb.png)

If not imported async the style is in the entry.

![image](https://user-images.githubusercontent.com/8287751/102274909-e8adaa00-3f24-11eb-9ff5-9361aef28a9c.png)

**Comment by AlMuz** [comment]
@ThornWalli  Hello! 
What about to add to the master those changes: import css from head to shadow css?

**Comment by ThornWalli** [comment]
@AlMuz Look at the version `1.8.0`, there the entry has now an option (`shadow`) to make the contained tags to `Shadow DOM` elements with styling.
